### ISSUE TITLE
HASH Encrypted

### ISSUE THREAD

**Issue by moe2501** [jilleb/mib2-toolbox#80] opened 2020-06-15 06:40 UTC
Can anybody Help! 
How can i encrypt HASH from FW. For Shell Login

**Comment by dfs-** [comment] 2020-07-18 11:59
You can extract the shadow file from the firmware update and then use a tool (i. e. Jack The Ripper) to decrypt the hash to retrieve the login password, yes.

**Comment by moe2501** [comment] 2020-07-18 12:04
what is the algorithm  do you have an example?  would be really great!  best regardsMoeCoding Bodensee Am 18.07.20 um 13:59 schrieb dfs-
                
            
            
                
                    Von: "dfs-" <notifications@github.com>Datum: 18. Juli 2020An: "jilleb/mib2-toolbox" <mib2-toolbox@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"moe2501" <moe-coding@web.de>Betreff: Re: [jilleb/mib2-toolbox] HASH Encrypted (#80)
                
                
You can extract the shadow file from the firmware update and then use a tool (i. e. Jack The Ripper) to decrypt the hash to retrieve the login password, yes.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jilleb/mib2-toolbox/issues/80#issuecomment-660472566",
"url": "https://github.com/jilleb/mib2-toolbox/issues/80#issuecomment-660472566",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dfs-** [comment] 2020-07-18 12:36
Should be DES with the first two letters of the hash being the IV.

**Comment by moe2501** [comment] 2020-07-18 18:01
Pulling the hash out of the FW is no problem!  just how do I do that with j.ripper!  which command do i need.MoeCoding Bodensee Am 18.07.20 um 14:36 schrieb dfs-
                
            
            
                
                    Von: "dfs-" <notifications@github.com>Datum: 18. Juli 2020An: "jilleb/mib2-toolbox" <mib2-toolbox@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"moe2501" <moe-coding@web.de>Betreff: Re: [jilleb/mib2-toolbox] HASH Encrypted (#80)
                
                
Should be DES with the first two letters of the hash being the IV.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jilleb/mib2-toolbox/issues/80#issuecomment-660476930",
"url": "https://github.com/jilleb/mib2-toolbox/issues/80#issuecomment-660476930",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by moe2501** [comment] 2020-07-20 09:33
Hello,

 

i need for Decrypting hash and salt? or only hash.

 

h3Urw56qsfAX2

 

I think that need so  many Time. Is this right?

i start it with John.

 

Warning: detected hash type "descrypt", but the string is also recognized as "descrypt-opencl"
Use the "--format=descrypt-opencl" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 1 password hash (descrypt, traditional crypt(3) [DES 128/128 AVX])
Will run 4 OpenMP threads
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, almost any other key for status
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:password.lst, rules:Wordlist
Proceeding with incremental:ASCII

 
 

Gesendet: Samstag, 18. Juli 2020 um 14:36 Uhr
Von: "dfs-" <notifications@github.com>
An: "jilleb/mib2-toolbox" <mib2-toolbox@noreply.github.com>
Cc: "moe2501" <moe-coding@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [jilleb/mib2-toolbox] HASH Encrypted (#80)


 

Should be DES with the first two letters of the hash being the IV.

**Comment by jilleb** [comment] 2020-09-03 08:24
I would start by googling the hash.
Closing this issue, as it's not a bug.

**Closed by jilleb** 2020-09-03 08:24 UTC
Labels: not a bug, offtopic
