### ISSUE TITLE
[REQUEST] Android Auto patch

### ISSUE THREAD

**Issue by Pepper9881** [jilleb/mib2-toolbox#107] opened 2020-11-14 16:18 UTC
Hi jilleb! I actively use your great program - thanks a lot for it!
Can I ask you to  make one more modification that will be useful to all owners of a digital dashboard? 
When the phone is connected via a mirrorlink, there is a great opportunity to use two navigation systems at the same time - the standard one on the dashboard and the telephone one on the MIB2HIGH screen. But if you connect via Android Auto, the built-in navigation is blocked and it cannot be displayed on the dashboard.
Can this blocking be disabled?

**Comment by jilleb** [comment] 2020-11-14 18:56
Working on it, but it's not an easy thing that can be achieved through the toolbox... This behavior is set inside mibroot, which means flashing a new ifs.

**Comment by Hamburgpriat** [comment] 2020-11-14 19:02
Waze is working on both Displays.

Pepper9881 <notifications@github.com> schrieb am Sa., 14. Nov. 2020, 17:18:

**Comment by Hamburgpriat** [comment] 2020-11-14 19:03
Waze is working on Both Displays. I dont know why this app is working on both.

**Comment by jilleb** [comment] 2020-11-14 19:17
Waze doesn't always work, sometimes it reports the mobile navigation to be active and sometimes it doesn't.

**Comment by andy0172** [comment] 2020-11-14 21:06
> Working on it, but it's not an easy thing that can be achieved through the toolbox... This behavior is set inside mibroot, which means flashing a new ifs.

Ifs flash is possible with the toolbox. Which bytes have to modified within mibroot?

**Comment by Pepper9881** [comment] 2020-11-21 11:18
> Working on it, but it's not an easy thing that can be achieved through the toolbox... This behavior is set inside mibroot, which means flashing a new ifs.

Have you any success to disable such behavior through mibroot patсhing?

**Comment by Pepper9881** [comment] 2020-11-21 11:23
> Waze is working on Both Displays. I dont know why this app is working on both.
Thank you! It's really interesting. Unfortunately, in my region, Waze not perfect with traffic and speedcam information

**Comment by olli991** [comment] 2021-01-26 23:29
Duplicate of #10 . Should be done if we fix carplay shut down of car maps.

**Comment by brianyou0524** [comment] 2021-01-27 06:55
I use MIB2 toolbox 4.0 to patch Android Auto successfully 
Could somebody share what custom 3rd party tool could be used for screen mirror? or any tool to play youtube?
As I know , if I root my phone , I could use AA mirror , but I don't want to root my phone and that's why I use toolbox to patch it

**Comment by jilleb** [comment] 2021-01-27 10:36
I use aa mirror.

Closing this because of duplicate.

**Closed by jilleb** 2021-01-27 10:36 UTC
Labels: duplicate
