### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by cristianbiris** [jilleb/mib2-toolbox#14] opened 2019-10-24 07:38 UTC
![IMG_20191024_103003](https://user-images.githubusercontent.com/36518317/67463311-dc43ff00-f649-11e9-9e31-014d02ec0702.jpg)
![IMG_20191024_103022](https://user-images.githubusercontent.com/36518317/67463322-e2d27680-f649-11e9-8941-ae2d7b5657ca.jpg)

Hello, 

When I'm trying to install it from the SD card I get the following error:
"Variant conflict"
"Medium: device doesn't support this (MainUnit: variant)"

My software version is 0363

Please let me know what you think could be the problem.. 

Thank you

**Comment by jilleb** [comment] 2019-10-24 07:51
Your unit is not an MIB2 High but Standard. You can see this at the train version: MST = MIB Standard

**Comment by cristianbiris** [comment] 2019-10-24 07:55
Thanks for the reply.
It seems that I'm out of luck with this... Or is there any chance this will be available for the standard version also in the future?

**Comment by jilleb** [comment] 2019-10-24 08:29
Closing this issue, duplicate of #7

**Closed by jilleb** 2019-10-24 08:29 UTC
