### ISSUE TITLE
Feature request: Possible to disable start-stop on Golf GTE?

### ISSUE THREAD

**Issue by kentherzz** [jilleb/mib2-toolbox#15] opened 2019-10-24 15:57 UTC
Hi Jille, is it possible to prevent the engine from stopping while in GTE-mode on a Golf GTE 2016-model, pre-facelift? # # #

**Comment by jilleb** [comment] 2019-10-24 18:57
Yes it is, but you would need modifications to the engine management for this. That will not be possible with this toolbox. The main purpose of this toolbox is changes to the infotainment, MIB2 High.

A tuner can turn the start/stop in GTE mode off. I will close this issue since it's not a bug or plausible feature request.

**Closed by jilleb** 2019-10-24 18:57 UTC

**Comment by kentherzz** [comment] 2019-10-24 19:01
Fair enough, so what is exactly required? Not possible with tools like VCP/VCDS?
