### ISSUE TITLE
Metainfo2.txt error

### ISSUE THREAD

**Issue by manuman06** [jilleb/mib2-toolbox#113] opened 2020-11-28 19:46 UTC
![20201129_151910](https://user-images.githubusercontent.com/75123267/100544877-702ac600-3261-11eb-8d54-c8bdffb61435.jpg)
Hello
I tried to install with a sdcard but I get metainfo2.txt error.
I read somewhere in a post that the same thing happened to others.
What to do? Did I do it wrong or what?
Thanks for doing a good job. I hope to succeed in installing the tool.

**Comment by faka001** [comment] 2021-01-01 09:29
Same case with me.

**Comment by jilleb** [comment] 2021-01-01 21:41
duplicate of #54  and #4 

It's nothing you did.. just a strange thing happening that I cannot reproduce myself.

**Comment by manuman06** [comment] 2021-01-01 21:46
What else can I try?

**Comment by jorgeth73** [comment] 2021-01-03 23:43
Same error to me!!...

**Closed** 2021-01-22 20:29 UTC
Labels: duplicate
