### ISSUE TITLE
[BUG] image car

### ISSUE THREAD

**Issue by titidu3131** [jilleb/mib2-toolbox#247] opened 2023-05-27 21:40 UTC
Bonjour j'ai fait la mise à jour de 253 vers 479 sur ma Leon Cupra tout fonctionne parfaitement sauf que j'ai l'image d'une Leon basique et impossible de remettre une Cupra même en suivant les guides sur internet
MST2 Tech H24
Une idée ? Merci ![ A6DFC496-487A-4AE6-82C2-BDC3ABC74947](https://github.com/jilleb/mib2-toolbox/assets/131201375/b0611d72-a277-4c2b-b607-56e7ec5fb75b)

**Comment by titidu3131** [comment] 2023-05-27 21:42
Hello I updated from 253 to 479 on my Leon Cupra everything works perfectly except that I have the image of a basic Leon and impossible to put a Cupra back even by following the guides on the internet
MST2 Tech H24
An idea ? THANKS

**Comment by jilleb** [comment] 2023-05-28 17:24
This toolbox is all about MIB2 High, and yours is the MIB2 Standard.

Have you checked your long coding, byte 18?
Closing this, as it's not a bug and not MIB2 High related.

**Closed by jilleb** 2023-05-28 17:24 UTC

**Comment by titidu3131** [comment] 2023-05-28 17:28
hello I'm really sorry I looked wrong.Le 28 mai 2023 à 19:24, Chillout ***@***.***> a écrit :﻿
Closed #247 as completed.

**Comment by titidu3131** [comment] 2023-05-28 19:41
Hello, I'm really sorry, I didn't put my message in the right place. What should I look for in byte 18? THANKS .Le 28 mai 2023 à 19:24, Chillout ***@***.***> a écrit :﻿
This toolbox is all about MIB2 High, and yours is the MIB2 Standard.
Have you checked your long coding, byte 18?
Closing this, as it's not a bug and not MIB2 High related.
