### ISSUE TITLE
[REQUEST] Don’t start CarPlay when connecting

### ISSUE THREAD

**Issue by andy0172** [jilleb/mib2-toolbox#205] opened 2022-03-05 16:56 UTC
By default a Harman unit will switch to appconnect as soon you connect the mobile. 

Due to I’m using a wireless box this is always connected and all then time starting CarPlay again. Would it be possible to just start with the last used screen instead of changing to CarPlay all the time?

**Comment by jilleb** [comment] 2022-04-13 09:03
Duplicate of #102

**Closed by jilleb** 2022-04-13 09:03 UTC
