### ISSUE TITLE
Metainfo signature problem with 1440

### ISSUE THREAD

**Issue by aes31** [jilleb/mib2-toolbox#33] opened 2020-01-24 19:41 UTC
Skoda Octavia 
Mib 2,5
SW 1440

Metainfo problem

![910A6D83-F80A-4052-8B3A-BFD9F5DBE8C9](https://user-images.githubusercontent.com/55639902/73098495-94f43580-3efa-11ea-9584-5fbb0307eb0f.jpeg)
![DE799550-2DEE-4119-ABA4-B87881BE2BBD](https://user-images.githubusercontent.com/55639902/73098497-958ccc00-3efa-11ea-9363-642e10f53f8c.jpeg)

**Comment by jilleb** [comment] 2020-01-25 10:12
I recently installed it on Skoda 1440, and it worked. So it's not the firmware version that's causing issues. Can you check the IOC version?

**Comment by aes31** [comment] 2020-01-25 14:55
What is IOC version?

**Comment by aes31** [comment] 2020-01-25 16:48
![FBC80802-D367-4DB9-9BCC-150374E46B71](https://user-images.githubusercontent.com/55639902/73124376-b2350c80-3fab-11ea-87fd-a53a4c12a044.png)

**Comment by jilleb** [comment] 2020-02-08 11:00
Duplicate of #1

**Closed by jilleb** 2020-02-08 11:00 UTC
