### ISSUE TITLE
[BUG] "Section common already exists" into ./metainfo2.txt

### ISSUE THREAD

**Issue by 1e1** [jilleb/mib2-toolbox#129] opened 2021-01-29 11:19 UTC
**Describe the bug**
The MIB2 can't read the SD card with the message "Section common already exists". 

**To Reproduce**
1. Download the release 4.0 => https://github.com/jilleb/mib2-toolbox/releases/tag/v4.0
2. Format a 32Go SD Card as exFAT
3. Unzip the downloaded release (on Mac) to a folder
4. Copy the content of the folder on the root of the SD Card
```bash
% ls /Volumes/VW-TOOLBOX
Custom		LICENSE		Toolbox		metainfo2.txt
Dump		README.md	Tools
```
5. Eject the SD Card
6. Go to the car
7. Switch on the MIB2
8. Hold the MENU button until a hidden black screen appears
```
Mode Service
------------------------------
  Update software/versions
  Versions HMI
  Codes of function (FEC, SWaP)
  ITR
```
9. Click on "Update software/versions"-like (<= was in French)
```
Select source
------------------------------
  CD
  USB device
  SD Card
```
10. Insert the SD Card
11. The "SD Card" menu item becomes *bold*
12. Click on "SD Card"
13. Get the error message
```
Fail to read the Info version file
Error while reading /opening the file

Section common already exists
```
14. And yes, [metainfo2.txt](https://github.com/jilleb/mib2-toolbox/commit/5d71babf911750da5f6d3148380b7dc09671f186#diff-9899e45f5360e4e5664f44eb15a17d89d931415f5b84a04c8ec4b2579a8ba48f) 2 section [common]

**Expected behavior**
One [common] section into ./metainfo2.txt
Can you merge them?

**Firmware(please complete the following information):**
 - Brand: VW
 - Hardware-type: H41
 - Version: 0475

**Additional context**
None

**Comment by andrewleech** [comment] 2021-01-29 11:53
Hello,
The duplicate common sections is an important part of the flaw we use to install the toolbox, it's worked on every unit tested so far - your one is clearly different 

On the software version screen, there should be a "SW Train" line, similar to "MHI2_ER_VWG11_S2125_1". What is your train?

**Comment by olli991** [comment] 2021-01-29 11:53
>
>Format a 32Go SD Card as exFAT
>
I would use FTA32 or NTFS.

>
>Section common already exists
>
This is actually the backdoor which infiltrates the system. So this have to be there ;-)

>
>Firmware(please complete the following information):
    Brand: VW
    Hardware-type: H41
    Version: 0475
>

This seems to be the real problem: You are nor unsing MHI2 or MIB2 High. This firmware version looks like MST2 which isn't currently supported by this toolbox.

**Comment by 1e1** [comment] 2021-01-29 13:11
Hi both, 

I'm sorry, my Train version is well MST2_EU_VW_PQ_P0475T… 
My bad I have not the right device :/ 

@olli991 I have just follow the pattern ;) 
I know my dealer has upgrade my software. This is a software issue or really the hardware? 
The car is a VW Sharan Sound Edition 2017

**Comment by andrewleech** [comment] 2021-01-29 13:19
That's interesting that you've just had the sw updated. I hoped the new install scheme in 4.0 might work on mst devices, I'll have to find one with older sw to see if the problem is mst or the new sw.

**Comment by 1e1** [comment] 2021-01-29 13:47
@andrewleech 
Depending the definition of "new". My device has been updated in January 2020.

**Comment by jilleb** [comment] 2021-02-06 21:45
closing this, as it's not a bug or feature request

**Comment by jilleb** [comment] 2021-02-06 21:46
But... kudos for the great and extensive description!!

**Closed by jilleb** 2021-02-06 21:45 UTC
Labels: MIB2STD is NOT supported.

**Comment by morpheus11** [comment] 2023-11-18 20:04
Hi dear Jilleb, I have the same problem with my 3q0 035 819.
Error MSG: "Section common already exist"
last train: MST2_EU_VW_ZR_P0480T
Jilleb, what am I doing wrong?

Thanks for You Best work)))Awesome

![czytnik-plyt-kart-SD-VW-PASSAT-B8-3Q0035819-Producent-czesci-Volkswagen-OE](https://github.com/jilleb/mib2-toolbox/assets/16577400/e4f26b51-bf8f-4fab-b3f5-cb84538edf62)
![03e58741-8c47-4198-87ec-b6a49c48ac38](https://github.com/jilleb/mib2-toolbox/assets/16577400/597baf33-9de9-4dec-b034-a9dfbe4cd176)

**Comment by morpheus11** [comment] 2023-11-18 20:20
> But... kudos for the great and extensive description!!

Hi dear Jilleb, I have the same problem with my 3q0 035 819.
Error MSG: "Section common already exist"
last train: MST2_EU_VW_ZR_P0480T
Jilleb, what am I doing wrong?

Thanks for You Best work)))Awesome

![czytnik-plyt-kart-SD-VW-PASSAT-B8-3Q0035819-Producent-czesci-Volkswagen-OE](https://github.com/jilleb/mib2-toolbox/assets/16577400/e4f26b51-bf8f-4fab-b3f5-cb84538edf62)
![03e58741-8c47-4198-87ec-b6a49c48ac38](https://github.com/jilleb/mib2-toolbox/assets/16577400/597baf33-9de9-4dec-b034-a9dfbe4cd176)

**Comment by jilleb** [comment] 2023-11-18 22:13
Thanks but please read the other supplied answers top 😅

**Comment by morpheus11** [comment] 2023-11-19 14:41
> Thanks but please read the other supplied answers too 😅

Jilleb seems to be for all the people coming from Google with the same problem described above.
better look for [MIBSTD2_Toolbox-v1.3.3](https://github.com/olli991/mib-std2-pq-zr-toolbox) from Olli991, is this correct?😅

**Comment by jilleb** [comment] 2023-11-19 15:12
Yes, that one is perfect 😎👌
